### ISSUE TITLE
Please Release Version: 3.5.0

### ISSUE THREAD

**Issue by randm-ch** [webjars/modernizr#6]
_Edit: Sorry, didn't see the other issues before opening this one. Please dismiss._

**Comment by jamesward** [comment]
I can't find a versioned, built artifact for this version.  Can you find one?

**Comment by randm-ch** [comment]
No, hence the edit. See discussion here: https://github.com/Modernizr/Modernizr/issues/1691
I guess in order to use it with WebJars we will have to use v2.x. Thanks for your time!

**Comment by jamesward** [comment]
Yeah, it is really unfortunately they don't provide a real release artifact.
